language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
script:
  - npm run check-dependency
  - npm run lint
  - npm run cover
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
